[features]
resolution = true
skip-lint = false

[programs.localnet]
ghbounty_escrow = "CPZx26QXs3HjwGobr8cVAZEtF1qGzqnNbBdt7h1EwbBg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/ghbounty-dev.json"

[scripts]
test = "cargo test"
